; =====================================================================
;  PHP-FPM — Master process configuration
; =====================================================================

[global]
pid = /var/run/php-fpm/php-fpm.pid
error_log = /dev/stderr
log_level = warning

; Daemonize off — Docker manages the process
daemonize = no

; Emergency restart if children crash
emergency_restart_threshold = 10
emergency_restart_interval = 1m
process_control_timeout = 10s

include=/usr/local/etc/php-fpm.d/*.conf
